-- HSK 6 Vocabulary Items (sort_order 101-2000)
-- Advanced vocabulary, chengyu, literary expressions, formal language

-- Words 101-150
INSERT INTO course_vocabulary_items (course_id, word_zh, word_pinyin, word_en, hsk_level, sort_order) VALUES
(c6, '贯彻', 'guànchè', 'implement, carry out', 6, 101),
(c6, '腐败', 'fǔbài', 'corruption, rotten', 6, 102),
(c6, '赋予', 'fùyǔ', 'bestow, endow', 6, 103),
(c6, '辅导', 'fǔdǎo', 'tutor, coach', 6, 104),
(c6, '概括', 'gàikuò', 'summarize, generalize', 6, 105),
(c6, '概念', 'gàiniàn', 'concept, notion', 6, 106),
(c6, '干旱', 'gānhàn', 'drought, arid', 6, 107),
(c6, '尴尬', 'gāngà', 'awkward, embarrassed', 6, 108),
(c6, '纲领', 'gānglǐng', 'program, guiding principle', 6, 109),
(c6, '港口', 'gǎngkǒu', 'port, harbor', 6, 110),
(c6, '高峰', 'gāofēng', 'peak, summit', 6, 111),
(c6, '告辞', 'gàocí', 'take leave, say goodbye', 6, 112),
(c6, '格局', 'géjú', 'pattern, structure', 6, 113),
(c6, '隔阂', 'géhé', 'estrangement, barrier', 6, 114),
(c6, '个体', 'gètǐ', 'individual, single entity', 6, 115),
(c6, '根深蒂固', 'gēnshēndìgù', 'deep-rooted, ingrained', 6, 116),
(c6, '耕地', 'gēngdì', 'arable land, cultivate', 6, 117),
(c6, '工艺', 'gōngyì', 'craft, technology', 6, 118),
(c6, '公摊', 'gōngtān', 'share public costs', 6, 119),
(c6, '攻克', 'gōngkè', 'capture, overcome', 6, 120),
(c6, '恭敬', 'gōngjìng', 'respectful, deferential', 6, 121),
(c6, '巩固', 'gǒnggù', 'consolidate, strengthen', 6, 122),
(c6, '贡献', 'gòngxiàn', 'contribution, dedicate', 6, 123),
(c6, '勾结', 'gōujié', 'collude, gang up', 6, 124),
(c6, '构思', 'gòusī', 'conception, conceive', 6, 125),
(c6, '孤独', 'gūdú', 'lonely, solitary', 6, 126),
(c6, '辜负', 'gūfù', 'fail to live up to, betray', 6, 127),
(c6, '估计', 'gūjì', 'estimate, reckon', 6, 128),
(c6, '骨干', 'gǔgàn', 'backbone, mainstay', 6, 129),
(c6, '鼓舞', 'gǔwǔ', 'inspire, hearten', 6, 130),
(c6, '固执', 'gùzhí', 'stubborn, obstinate', 6, 131),
(c6, '雇佣', 'gùyōng', 'employ, hire', 6, 132),
(c6, '刮风', 'guāfēng', 'wind blows', 6, 133),
(c6, '挂念', 'guàniàn', 'worry about, miss', 6, 134),
(c6, '拐弯', 'guǎiwān', 'turn a corner', 6, 135),
(c6, '关怀', 'guānhuái', 'show loving care', 6, 136),
(c6, '观摩', 'guānmó', 'observe and learn from', 6, 137),
(c6, '官僚', 'guānliáo', 'bureaucrat, bureaucracy', 6, 138),
(c6, '冠军', 'guànjūn', 'champion, first place', 6, 139),
(c6, '灌溉', 'guàngài', 'irrigate, irrigation', 6, 140),
(c6, '光辉', 'guānghuī', 'radiance, glory', 6, 141),
(c6, '广泛', 'guǎngfàn', 'extensive, widespread', 6, 142),
(c6, '规范', 'guīfàn', 'standard, norm', 6, 143),
(c6, '规划', 'guīhuà', 'plan, program', 6, 144),
(c6, '规模', 'guīmó', 'scale, scope', 6, 145),
(c6, '归根到底', 'guīgēndàodǐ', 'in the final analysis', 6, 146),
(c6, '归纳', 'guīnà', 'sum up, induce', 6, 147),
(c6, '轨道', 'guǐdào', 'track, orbit', 6, 148),
(c6, '滚动', 'gǔndòng', 'roll, rolling', 6, 149),
(c6, '锅炉', 'guōlú', 'boiler, furnace', 6, 150);

-- Words 151-200
INSERT INTO course_vocabulary_items (course_id, word_zh, word_pinyin, word_en, hsk_level, sort_order) VALUES
(c6, '果断', 'guǒduàn', 'resolute, decisive', 6, 151),
(c6, '过渡', 'guòdù', 'transition, transitional', 6, 152),
(c6, '过滤', 'guòlǜ', 'filter, screen', 6, 153),
(c6, '海拔', 'hǎibá', 'altitude, elevation', 6, 154),
(c6, '海关', 'hǎiguān', 'customs', 6, 155),
(c6, '含糊', 'hánhu', 'ambiguous, vague', 6, 156),
(c6, '含义', 'hányì', 'meaning, implication', 6, 157),
(c6, '罕见', 'hǎnjiàn', 'rare, seldom seen', 6, 158),
(c6, '捍卫', 'hànwèi', 'defend, safeguard', 6, 159),
(c6, '行列', 'hángliè', 'ranks, procession', 6, 160),
(c6, '豪迈', 'háomài', 'bold and generous', 6, 161),
(c6, '耗费', 'hàofèi', 'consume, expend', 6, 162),
(c6, '合并', 'hébìng', 'merge, combine', 6, 163),
(c6, '合成', 'héchéng', 'synthesize, compound', 6, 164),
(c6, '合理', 'hélǐ', 'reasonable, rational', 6, 165),
(c6, '和蔼', 'hé''ǎi', 'kindly, affable', 6, 166),
(c6, '和睦', 'hémù', 'harmonious, on good terms', 6, 167),
(c6, '核心', 'héxīn', 'core, nucleus', 6, 168),
(c6, '恨不得', 'hènbude', 'wishing one could', 6, 169),
(c6, '横', 'héng', 'horizontal, across', 6, 170),
(c6, '哄堂大笑', 'hōngtángdàxiào', 'roar with laughter', 6, 171),
(c6, '宏观', 'hóngguān', 'macro, macroscopic', 6, 172),
(c6, '宏伟', 'hóngwěi', 'grand, magnificent', 6, 173),
(c6, '喉咙', 'hóulóng', 'throat, larynx', 6, 174),
(c6, '后顾之忧', 'hòugùzhīyōu', 'worries about the future', 6, 175),
(c6, '呼啸', 'hūxiào', 'whistle, scream', 6, 176),
(c6, '忽略', 'hūlüè', 'neglect, overlook', 6, 177),
(c6, '胡说', 'húshuō', 'nonsense, talk rubbish', 6, 178),
(c6, '胡同', 'hútòng', 'alley, lane', 6, 179),
(c6, '花费', 'huāfèi', 'spend, expend', 6, 180),
(c6, '华丽', 'huálì', 'gorgeous, magnificent', 6, 181),
(c6, '滑稽', 'huájī', 'funny, comical', 6, 182),
(c6, '化肥', 'huàféi', 'chemical fertilizer', 6, 183),
(c6, '化石', 'huàshí', 'fossil', 6, 184),
(c6, '化验', 'huàyàn', 'laboratory test', 6, 185),
(c6, '划分', 'huàfēn', 'divide, differentiate', 6, 186),
(c6, '怀念', 'huáiniàn', 'cherish memory of, miss', 6, 187),
(c6, '缓和', 'huǎnhé', 'ease, mitigate', 6, 188),
(c6, '患者', 'huànzhě', 'patient, sufferer', 6, 189),
(c6, '荒凉', 'huāngliáng', 'desolate, barren', 6, 190),
(c6, '荒谬', 'huāngmiù', 'absurd, preposterous', 6, 191),
(c6, '慌张', 'huāngzhāng', 'flustered, nervous', 6, 192),
(c6, '皇帝', 'huángdì', 'emperor', 6, 193),
(c6, '辉煌', 'huīhuáng', 'splendid, glorious', 6, 194),
(c6, '挥霍', 'huīhuò', 'squander, waste', 6, 195),
(c6, '恢复', 'huīfù', 'restore, recover', 6, 196),
(c6, '汇报', 'huìbào', 'report, give account', 6, 197),
(c6, '贿赂', 'huìlù', 'bribe, bribery', 6, 198),
(c6, '昏迷', 'hūnmí', 'coma, unconscious', 6, 199),
(c6, '浑身', 'húnshēn', 'all over the body', 6, 200);
